/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Biaoda: typeof import('./src/components/biaoda.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
